AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Innovator Island - 6 Event-based architecture - Part 1.
Globals:
  Function:
    Timeout: 10
Resources:
  MetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://theme-park-sam-deploys-008744601422/c7e2236d620aa053862333533510dbb2
      Handler: example.Handler::handleRequest
      Runtime: java11
      MemorySize: 128
      Policies:
      - Statement:
        - Effect: Allow
          Resource: '*'
          Action:
          - cloudwatch:PutMetricData
