AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: module3-controller
Parameters:
  DynamoDBTableName:
    Type: String
    Description: Main Theme Park app table
  IOTendpoint:
    Type: String
    Description: Theme Park IoT endpoint
Globals:
  Function:
    Timeout: 3
Resources:
  ControllerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://theme-park-sam-deploys-008744601422/17beb031b44339192a1f266456f1682e
      Handler: app.handler
      MemorySize: 128
      Runtime: nodejs14.x
      Environment:
        Variables:
          DDB_TABLE_NAME:
            Ref: DynamoDBTableName
          IOT_DATA_ENDPOINT:
            Ref: IOTendpoint
          IOT_TOPIC: theme-park-rides
      Policies:
      - Statement:
        - Effect: Allow
          Resource: '*'
          Action:
          - iot:*
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTableName
    Metadata:
      SamResourceId: ControllerFunction
Outputs:
  ControllerFunctionArn:
    Export:
      Name: ControllerFunctionARN
    Value:
      Fn::GetAtt:
      - ControllerFunction
      - Arn
